#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
#RUN mkdir Reporting.API
#COPY ./Reporting.API/Reporting.API.csproj ./Reporting.API/
#RUN dotnet restore "Reporting.API/Reporting.API.csproj"
COPY . .
RUN dotnet restore "Reporting.sln"
RUN dotnet build "Reporting.sln"
RUN dotnet test "Reporting.UnitTest/Reporting.UnitTest.csproj"
RUN dotnet test "Reporting.IntegrationTest/Reporting.IntegrationTest.csproj"
#WORKDIR "/src/Reporting.API"
RUN dotnet build "Reporting.API/Reporting.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Reporting.API/Reporting.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Reporting.API.dll"]
