# Default values for darwin-reporting-api
# This file is in YAML format
# Declared variables to be passed into $/templates files

appName: reporting-api
namespace: qe01

image:
  repository: 929380036510.dkr.ecr.us-east-1.amazonaws.com/reporting-api
  tag: qa
  pullPolicy: Always

imagePullSecrets: []

service:
  type: NodePort
  port: 80

ingress:
  external:
    sslRedirect: "false"
    forceSslRedirect: "true"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 384Mi

# replicacount has no impact if autoscaling.enabled = true
replicacount: 1
autoscaling:
  enabled: false

env_vars:
  data:
    LOG_JSON: "true"
    LOG_MINIMUMLEVEL: Information
    MONGO_DB_NAME: reporting-api-qe01
    USERS_API_BASE_URL: "http://users-api/api/v4/users"
    TRAINING_PROGRAM_API_BASE_URL: "https://learning-objects.dev.sgp.wiley.host/v4/training-programs"
    COMPANY_API_BASE_URL: "http://company-api/api/v1/organizations"
    KEYCLOAK_BASE_URL: "https://keycloak.qe01.sgp.wiley.host"
    KEYCLOAK_REALM: "darwin"
    KEYCLOAK_AUDIENCE: "account"
    GRANT_TYPE: "client_credentials"
    CLIENT_ID: "d2c7f2d6-eba6-4a32-8c0d-a704a20d9c73"
    RESOURCE: "https://analysis.windows.net/powerbi/api"
    AZURE_URL: "https://login.microsoftonline.com/24fe244f-890e-46ef-be2f-a5202976b7a5/oauth2/token"
    POWERBI_API_URL: "https://api.powerbi.com/v1.0/myorg/groups/"
    DATASET_ID: "d250fc4d-11be-46e2-b1c9-0fb6ea9dd787"
    USER_API_URL: "https://users-api.qe01.sgp.wiley.host/api/v4/"
    OPA_BASE_URL: "https://opa.qe01.sgp.wiley.host"

externalsecrets:
  refreshInterval: 1m
  secretCreationPolicy: Owner
  secretStoreName: eks-nonprod-us-secret-manager
  secretStoreType: ClusterSecretStore
  data:
  - keyValue: qe/darwin/secrets
    nameValue: COMPANY_API_KEY
    propertyValue: COMPANY_API_KEY
  - keyValue: qe/darwin/secrets
    nameValue: MONGO_CONNECTION_STRING
    propertyValue: REPORTING_API_QE01_MONGO_CONNECTION_STRING
  - keyValue: qe/darwin/secrets
    nameValue: API_KEY
    propertyValue: REPORTING_API_KEY
  - keyValue: qe/darwin/secrets
    nameValue: CLIENT_SECRET
    propertyValue: REPORTING_CLIENT_SECRET