apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
  annotations:

    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: phoenix-{{ .Values.appName }}.{{ .Values.dns.externalCk }}
    ingress.kubernetes.io/ssl-redirect:  "{{ .Values.ingress.external.sslRedirect }}"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "{{ .Values.ingress.external.forceSslRedirect }}"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: phoenix-{{ .Values.appName }}.{{ .Values.dns.externalCk }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: 80
